name: Update sitemap lastmod

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-lastmod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Update sitemap lastmod
        run: node scripts/update-sitemap-lastmod.js
      - name: Commit and push changes (if any)
        run: |
          if [[ -n "$(git status --porcelain sitemap.xml)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add sitemap.xml
            git commit -m "chore(ci): update sitemap <lastmod> via GitHub Actions"
            git push
          else
            echo "No changes to commit."
          fi

